global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: toolbox-otel
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          db_system: postgresql
          db_cluster: local
          db_instance: postgres-1
          db_role: primary
          environment: local

  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          db_system: redis
          db_cluster: local
          db_instance: redis-1
          db_role: primary
          environment: local

  - job_name: mongodb
    static_configs:
      - targets: ["mongodb-exporter:9216"]
        labels:
          db_system: mongodb
          db_cluster: local
          db_instance: mongodb-1
          db_role: primary
          environment: local
